import React, { useState, useMemo } from 'react';
import { Plus, Trash2, Save, Download, Github } from 'lucide-react';
import type { FlatFiles } from '../types';

interface EnvPanelProps {
  files: FlatFiles;
  onUpdateFile: (path: string, content: string) => void;
  onImportFromGitHub?: (owner: string, repo: string, branch: string) => Promise<void>;
  embedded?: boolean;
}

interface EnvVar {
  key: string;
  value: string;
}

const ENV_FILE_CANDIDATES = ['.env', '.env.local', '.env.development', '.env.production', '.env.example'];

export function EnvPanel({ files, onUpdateFile, onImportFromGitHub, embedded = false }: EnvPanelProps) {
  const [selectedFile, setSelectedFile] = useState('.env');
  const [newKey, setNewKey] = useState('');
  const [newValue, setNewValue] = useState('');
  const [importOwner, setImportOwner] = useState('');
  const [importRepo, setImportRepo] = useState('');
  const [importBranch, setImportBranch] = useState('main');
  const [importing, setImporting] = useState(false);

  // Find existing .env* files
  const envFiles = useMemo(() => {
    return Object.keys(files).filter((p) => p.startsWith('.env') || p === '.env.example');
  }, [files]);

  const currentEnvFile = envFiles.includes(selectedFile) ? selectedFile : (envFiles[0] || '.env');

  // Parse current env file
  const envContent = files[currentEnvFile] || '';
  const vars: EnvVar[] = useMemo(() => {
    return envContent
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#'))
      .map((line) => {
        const [key, ...rest] = line.split('=');
        return { key: key.trim(), value: rest.join('=').trim().replace(/^["']|["']$/g, '') };
      })
      .filter((v) => v.key);
  }, [envContent]);

  const updateEnvFile = (newVars: EnvVar[]) => {
    const content = [
      '# Generated by Mini Blitz Env Panel',
      ...newVars.map((v) => `${v.key}=${v.value.includes(' ') ? `"${v.value}"` : v.value}`),
    ].join('\n');
    onUpdateFile(currentEnvFile, content);
  };

  const addVar = () => {
    if (!newKey.trim()) return;
    const updated = [...vars, { key: newKey.trim(), value: newValue.trim() }];
    updateEnvFile(updated);
    setNewKey('');
    setNewValue('');
  };

  const updateVar = (index: number, field: 'key' | 'value', val: string) => {
    const updated = [...vars];
    updated[index] = { ...updated[index], [field]: val };
    updateEnvFile(updated);
  };

  const deleteVar = (index: number) => {
    const updated = vars.filter((_, i) => i !== index);
    updateEnvFile(updated);
  };

  const createEnvFile = (name: string) => {
    if (!files[name]) {
      onUpdateFile(name, '# Add your environment variables here\n');
      setSelectedFile(name);
    }
  };

  // GitHub import
  const handleGitHubImport = async () => {
    if (!importOwner || !importRepo || !onImportFromGitHub) return;
    setImporting(true);
    try {
      await onImportFromGitHub(importOwner.trim(), importRepo.trim(), importBranch.trim() || 'main');
    } catch (e: any) {
      alert('GitHub import failed: ' + (e.message || e));
    } finally {
      setImporting(false);
    }
  };

  return (
    <div className="flex h-full flex-col bg-[#111] text-sm">
      <div className="flex items-center gap-2 border-b border-white/10 px-3 py-2 text-xs font-medium text-white/70">
        <span>ENV VARIABLES</span>
        <select
          value={currentEnvFile}
          onChange={(e) => setSelectedFile(e.target.value)}
          className="ml-auto rounded bg-black/40 px-1 py-0.5 text-xs"
        >
          {envFiles.length > 0 ? (
            envFiles.map((f) => (
              <option key={f} value={f}>{f}</option>
            ))
          ) : (
            <option value=".env">.env (new)</option>
          )}
        </select>
        <button
          onClick={() => createEnvFile('.env.local')}
          className="text-[10px] text-white/50 hover:text-white"
          title="Create .env.local"
        >
          + local
        </button>
      </div>

      {/* Variables editor */}
      <div className="flex-1 overflow-auto p-3">
        <div className="mb-2 flex items-center justify-between text-[10px] uppercase tracking-widest text-white/50">
          <span>Variables in {currentEnvFile}</span>
          <button onClick={() => createEnvFile(currentEnvFile)} className="text-white/50 hover:text-white">
            <Plus className="h-3 w-3" />
          </button>
        </div>

        {vars.length === 0 && (
          <div className="mb-3 text-xs text-white/40">No variables yet. Add below or import from GitHub.</div>
        )}

        <div className="space-y-1">
          {vars.map((v, i) => (
            <div key={i} className="flex items-center gap-2 rounded bg-white/5 p-1.5 text-xs">
              <input
                value={v.key}
                onChange={(e) => updateVar(i, 'key', e.target.value)}
                className="w-1/3 rounded bg-black/40 px-1.5 py-0.5 font-mono text-white/90"
                placeholder="KEY"
              />
              <input
                value={v.value}
                onChange={(e) => updateVar(i, 'value', e.target.value)}
                className="flex-1 rounded bg-black/40 px-1.5 py-0.5 font-mono text-white/90"
                placeholder="value"
              />
              <button onClick={() => deleteVar(i)} className="text-white/40 hover:text-red-400">
                <Trash2 className="h-3.5 w-3.5" />
              </button>
            </div>
          ))}
        </div>

        {/* Add new */}
        <div className="mt-2 flex items-center gap-2">
          <input
            value={newKey}
            onChange={(e) => setNewKey(e.target.value)}
            placeholder="NEW_KEY"
            className="w-1/3 rounded bg-black/30 px-1.5 py-1 text-xs"
            onKeyDown={(e) => { if (e.key === 'Enter') addVar(); }}
          />
          <input
            value={newValue}
            onChange={(e) => setNewValue(e.target.value)}
            placeholder="value"
            className="flex-1 rounded bg-black/30 px-1.5 py-1 text-xs"
            onKeyDown={(e) => { if (e.key === 'Enter') addVar(); }}
          />
          <button onClick={addVar} className="rounded bg-white/10 px-2 py-1 text-xs hover:bg-white/20">
            Add
          </button>
        </div>

        <div className="mt-4 border-t border-white/10 pt-3">
          <div className="mb-1 text-[10px] uppercase tracking-widest text-white/50">GitHub Import</div>
          <div className="flex flex-col gap-1.5 text-xs">
            <div className="flex gap-1">
              <input
                value={importOwner}
                onChange={(e) => setImportOwner(e.target.value)}
                placeholder="owner"
                className="flex-1 rounded bg-black/30 px-1.5 py-1"
              />
              <input
                value={importRepo}
                onChange={(e) => setImportRepo(e.target.value)}
                placeholder="repo"
                className="flex-1 rounded bg-black/30 px-1.5 py-1"
              />
            </div>
            <div className="flex gap-1">
              <input
                value={importBranch}
                onChange={(e) => setImportBranch(e.target.value)}
                placeholder="branch (main)"
                className="flex-1 rounded bg-black/30 px-1.5 py-1"
              />
              <button
                onClick={handleGitHubImport}
                disabled={!importOwner || !importRepo || importing || !onImportFromGitHub}
                className="flex items-center gap-1 rounded bg-white/10 px-2 py-1 hover:bg-white/20 disabled:opacity-50"
              >
                <Github className="h-3 w-3" /> {importing ? 'Importing...' : 'Import'}
              </button>
            </div>
            <div className="text-[10px] text-white/40">
              Imports public repo files into current project (overwrites matching paths).
            </div>
          </div>
        </div>
      </div>

      <div className="border-t border-white/10 p-2 text-[10px] text-white/40">
        Changes are written to the WebContainer. Restart dev server after editing .env files for Vite to pick up new vars.
      </div>
    </div>
  );
}
